### ISSUE TITLE
"Error: listen EADDRINUSE" for Node v20.13.0 and above

### ISSUE THREAD

**Issue by timo-peakfijn** [swan-io/swan-partner-frontend#827]
After setting up the project on a new machine (MPro M3 Max) I noticed that the frontend project cannot be run on Node version v20.13.0 and above. I had installed the latest LTS version of Node, v20.15.1. But when running `yarn dev` gave me the following error:
```
Error: listen EADDRINUSE: address already in use 0.0.0.0:63237
    at Http2SecureServer.setupListenHandle [as _listen2] (node:net:1898:16)
    at listenInCluster (node:net:1946:12)
    at doListen (node:net:2116:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 63237
}
```

It took me a while to discover the issue, but eventually I ended up downgrading Node to match my previous machine and then it all worked as expected. I did some testing and it seems that the error appears from v20.13.0 and above

**Comment by bloodyowl** [comment]
from what I make of the issue, it seems to be related to https://github.com/nodejs/node/issues/53204

I'll investigate further, in the meantime let's use at most `20.12.2`

**Comment by bloodyowl** [comment]
@timo-peakfijn that should be better now (tested on v22.7.0)
